apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  namespace: jmeter
  labels:
    run: bb
  name: bb
spec:
  nodeName: kube-node-64ca
  containers:
  - image: busybox
    name: bb
    command: ["sh","-c","sleep 3600"]
    volumeMounts:
      - name:  mysql-pv-claim
        mountPath:  "/opt/results"
  volumes:
  - name: mysql-pv-claim
    persistentVolumeClaim:
      claimName: mysql-pv-claim         
  restartPolicy: Never