apiVersion: v1
kind: Pod
metadata:
  labels:
    run: bb
  name: bb
spec:
  containers:
  - image: busybox
    name: bb
    command: ["sh","-c","sleep 3600"]
    volumeMounts:
      - name:  jmeter-pv-claim
        mountPath:  "/opt/results"
  volumes:
  - name: jmeter-pv-claim
    persistentVolumeClaim:
      claimName: jmeter-pv-claim         
  restartPolicy: Never