apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jmeter-pv-claim
  labels:
    type: longhorn
    app: jmeter
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi